theme: jekyll-theme-minimal
title: e-Puppy â€” Your Everyday Companion
description: Developed by Team G Square for the final project. A smart robotic puppy with sensing, motion, and interactive features.
